#!bin/bash

set -euo pipefail

# set dotfiles path
DOTPATH="$HOME/.dotfiles"

## functions
info() { 
  
  echo "$1"
}

error() {
  
  echo "$1"
}

warn() {
  
  echo "$1"
}

log() { 

  echo "$1"
}

# Start install
read -p "$(warn 'Are you sure you want to install it? [y/N] ')" -n 1 -r
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
  echo ""
  error "Close the installer"
  exit 1
fi
echo ""

## Start the dotfiles install
info "Start the dotfiles install [1/10]"
if [ -d "$DOTPATH" ]; then
  error "The dotfiles directory already exists! Please command \"rm -r $HOME/.dotfiles\""
  exit 1
fi

info "Downloading the dotfiles [2/10]"
if [ -x "$(command type git)" ]; then
  git clone --recursive "https://github.com/wheson/dotfiles.git" "${DOTPATH}"
else
  tarball="https://github.com/wheson/dotfiles/archive/master.tar.gz"
  if [ -x "$(command type curl)" ]; then
    curl -L "$tarball"
  elif [ -x "$(command type wget)" ]; then
    wget -O - "$tarball"
  else
    error "Failed to download the dotfiles. Please install git, curl or wget."
    exit 1
  fi | tar xv -

  mv -f dotfiles-master "${DOTPATH}"
fi
info "Completed download the dotfiles [3/10]"

DOTPATH=~/.dotfiles; export DOTPATH

cd $DOTPATH
## Symbolic link
make link

## Exec init scripts
make init
