# cpp
[[plugins]]
repo = 'vim-jp/vim-cpp'
on_ft = 'cpp'

# ruby
[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = 'ruby'

# toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# json
[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
